Back:
  - "apps/api/**/*"
Front:
  - "apps/web/**/*"
Dependencies:
  - "apps/web/package.json"
  - "apps/web/yarn.lock"
  - "tools/playwright/package.json"
  - "tools/playwright/yarn.lock"
  - "apps/api/composer.json"
  - "apps/api/composer.lock"
Docker:
  - "**/*/Dockerfile"
  - "docker-compose*.yml"
TypeScript:
  - "**/*.ts"
  - "**/*.tsx"
Documentation:
  - "README.md"
  - "doc/**/*"
JavaScript:
  - "**/*.js"
PHP:
  - "**/*.php"
Test:
  - "**/*.spec.*"
  - "**/*Spec.*"
  - "**/*.test.*"