doctrine:
    dbal:
        driver: pdo_mysql
        host: "%env(MYSQL_HOST)%"
        port: "%env(MYSQL_PORT)%"
        dbname: "%env(MYSQL_DATABASE)%"
        user: "%env(MYSQL_USER)%"
        password: "%env(MYSQL_PASSWORD)%"
        server_version: "%env(MYSQL_VERSION)%"
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collation: utf8mb4_unicode_ci

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Model:
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/Model'
                prefix: "Domain\\Model"

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
